apiVersion: v1
kind: Pod
metadata:
  name: "task-pv-pod"
  # namespace: default
  # labels:
  #   app: "task-pv-pod"
spec:
  containers:
  - name: task-pv-pod
    image: "nginx"
    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 500Mi
    #   requests:
    #     cpu: 100m
    #     memory: 200Mi
    # env:
    # - name: DB_HOST
    #   valueFrom:
    #     configMapKeyRef:
    #       name: task-pv-pod
    #       key: DB_HOST
    ports:
      - containerPort:  80
        name:  http
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-storage
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  restartPolicy: Always